name = "social-image-builder"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"
account_id = "5cce5bcc5bb96f83ffc0409cafce4a11"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "social-image-builder-db"
database_id = "be2bcfcd-65f7-4cd1-803a-80dcbe88e1ea"
migrations_dir = "./drizzle"
